spring:
  kafka:
    bootstrap-servers: kafka-cluster-kafka-bootstrap.kafka.svc.cluster.local:9092
  datasource:
    url: jdbc:mysql://mysql-cluster:6446/dongdong?characterEncoding=utf8
    username: root
    password: 123456