apiVersion: mysql.oracle.com/v2alpha1
kind: InnoDBCluster
metadata:
  name: mysql-cluster
spec:
  secretName: mysql-secret
  version: 8.0.27
  datadirVolumeClaimTemplate:
    accessModes:
      - ReadWriteOnce
    storageClassName: longhorn
    resources:
      requests:
        storage:
          1Gi
  instances: 1
  router:
    instances: 1
---
apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
type: Opaque
stringData:
  rootUser: "root"
  rootHost: '%'
  rootPassword: "123456"
